#!/usr/bin/env php
<?php

// Load dependencies
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

new Phake\Run();
